### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by phile314** [abhinav/pinch#40]
I plan to make a new release once all the thrift server/client changes are done. That release would be compatible with the first release of https://github.com/phile314/pinch-gen/ .

TODOs:
- [x] Multiplex Client #39 
- [x] Export helper functions #38 
- [x] Wrap function #36 
- [x] Allow `ThriftServer` to throw `ApplicationException` properly #41
- [x] Crash connection if server receives wrong message type (!=Call/Oneway) #42
- [x] Check haddock
- [x] Changelog #43 
- [x] Make release https://hackage.haskell.org/package/pinch-0.4.0.0

**Comment by phile314** [comment]
Done: https://hackage.haskell.org/package/pinch-0.4.0.0

**Comment by abhinav** [comment]
Sweet! Congrats and thanks!

**Comment by phile314** [comment]
Thanks for all the code reviews from your side, it is greatly appreciated :smiley:
